### ISSUE TITLE
EOS generic cipher

### ISSUE THREAD

**Issue by avrnv** [Seagate/cortx-py-utils#1]
Introduces generic EOS symmetric ciphers. Basically they're just wrappers around Fernet. Wrappers are done to easily replace Fernet without changing the API if necessary.
Also the initial build and installation support are added.
README.md is updated accordingly with the build & installation instructions.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Already fixed / code merged

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. The required code is already part of current repo. Hence marking as fixed/no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
