### ISSUE TITLE
Eos cipher fix

### ISSUE THREAD

**Issue by avrnv** [Seagate/cortx-py-utils#2]
Fix the package name in README.md
Remove 'self' from Cipher methods that became static.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

The fix is already merged

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. The required code is already merged & part of current repo. Hence marking it as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
