### ISSUE TITLE
added cleanup folder in package

### ISSUE THREAD

**Issue by mazinamdar** [Seagate/cortx-py-utils#22]
added cleanup folder in package

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.
Marking this as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
