### ISSUE TITLE
args.yaml raise error if trying to access list element

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-py-utils#25]
No description provided.

**Comment by cortx-admin** [comment]
> Swarajya Pendharkar commented in Jira Server:

Original github issue is closed.

**Comment by cortx-admin** [comment]
> Swarajya Pendharkar commented in Jira Server:

Original github issue is closed.

**Comment by cortx-admin** [comment]
> Swarajya Pendharkar commented in Jira Server:

Original github issue is closed.

**Comment by cortx-admin** [comment]
> Swarajya Pendharkar commented in Jira Server:

Original github issue is closed.

**Comment by cortx-admin** [comment]
> Swarajya Pendharkar commented in Jira Server:

Original github issue is closed.
