### ISSUE TITLE
Use graph insted of compiled json

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-py-utils#36]
Use graph insted of compiled json in generate.py file to deal with resource operation.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

Marking this as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
