### ISSUE TITLE
EOS-6214: add indexes mapping types for indexes creation scheme

### ISSUE THREAD

**Issue by dmitrydb** [Seagate/cortx-py-utils#40]
Fix problem which causes index creation issue in ElasticSearch 6.8

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

Marking this as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
