### ISSUE TITLE
Replace res with resource

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-py-utils#55]
https://github.com/Seagate/py-utils/commit/863fc11f9edd2b0522f9ead298a92ed2b8f2d8c7#note_97017

Replace res with resource

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

Marking as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

No verification needed.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

No verification needed.
