### ISSUE TITLE
[BETA] EOS-7691 move delete index from csm

### ISSUE THREAD

**Issue by navalkp** [Seagate/cortx-py-utils#59]
moved delete index from csm

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug is from old/stale repo. Required code is already merged.

Marking as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

No verification needed.
