### ISSUE TITLE
audit log rotation

### ISSUE THREAD

**Issue by mazinamdar** [Seagate/cortx-py-utils#6]
Delete older data from given index.

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Code already merged in old repo

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This is from old/stale repo. The required code is already merged. Marking this as no work

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Bug from old repo, closing
