### ISSUE TITLE
EOS-7798: Adding support for NW Cable and filtered BMC alerts

### ISSUE THREAD

**Issue by pawankumarsrivastava** [Seagate/cortx-py-utils#62]
No description provided.

**Comment by cortx-admin** [comment]
> Chetan Deshmukh commented in Jira Server:

[~934747] what this ticket is about, seems to be 0created by you from git, 1 year back. Assigning it to you / CSM to close

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

Issue addressed

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

Issue addressed

**Comment by cortx-admin** [comment]
> Pawan Kumar Srivastava commented in Jira Server:

Issue addressed
