### ISSUE TITLE
Py utils data files causing permission denited in user

### ISSUE THREAD

**Issue by ajay-paratmandali** [Seagate/cortx-py-utils#64]
/node_status.py to node_status.cpython-36.pyc
    byte-compiling /opt/seagate/eos/csm/home/.local/lib/python3.6/site-packages/eos/utils/ha/__init__.py to __init__.cpython-36.pyc
    running install_data
    copying src/utils/ha/hac/specs/consul.json -> /var/lib/eos/ha/specs
    error: could not delete '/var/lib/eos/ha/specs/consul.json': Permission denied

------------------------------------------------------------------------------------------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-go324qua-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-suihy9g2-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-go324qua-build/

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

Invalid bug

**Comment by cortx-admin** [comment]
> Sachin Chandrakant Punadikar commented in Jira Server:

This bug was from old/stale repo, hence marking as invalid bug, no work
