### ISSUE TITLE
[Kafka Message Bus] Add a provision to take config path as an input parameter 

### ISSUE THREAD

**Issue by pawankumarsrivastava** [Seagate/cortx-py-utils#78]
For MessageBusComm class add one more field for taking configuration path as a parameter.

**Comment by cortx-admin** [comment]
> Selva Kumar Nambi commented in Jira Server:

MessageBusComm class is a very stale code and no word is needed.
However with new MessageBus.init configuration is passed as a parameter only.

**Comment by cortx-admin** [comment]
> Selva Kumar Nambi commented in Jira Server:

No work needed

**Comment by cortx-admin** [comment]
> Selva Kumar Nambi commented in Jira Server:

Verified.
